alter table public.plant_pv_changes
  add column id bigint generated by default as identity,
  add column plant_id text,
  add column type text;

with ordered_changes as (
  select
    spending_id,
    row_number() over (order by date, spending_id) as event_id
  from public.plant_pv_changes
)
update public.plant_pv_changes changes
set id = ordered_changes.event_id
from ordered_changes
where ordered_changes.spending_id = changes.spending_id;

select setval(
  pg_get_serial_sequence('public.plant_pv_changes', 'id'),
  coalesce(max(id), 1),
  max(id) is not null
)
from public.plant_pv_changes;

alter table public.plant_pv_changes
  alter column id set generated always;

update public.plant_pv_changes changes
set
  plant_id = spendings.plant_id,
  type = spendings.type
from public.plant_spendings spendings
where spendings.id = changes.spending_id;

alter table public.plant_pv_changes
  drop constraint plant_pv_changes_pkey,
  drop constraint plant_pv_changes_spending_id_fkey,
  alter column spending_id drop not null,
  alter column plant_id set not null,
  alter column type set not null,
  add constraint plant_pv_changes_pkey primary key (id),
  add constraint plant_pv_changes_plant_id_fkey
    foreign key (plant_id) references public.plants(id) on delete cascade,
  add constraint plant_pv_changes_spending_id_fkey
    foreign key (spending_id) references public.plant_spendings(id) on delete set null,
  add constraint plant_pv_changes_type_check
    check (type in ('improvement', 'damage_replacement'));

create index plant_pv_changes_plant_date_id_idx
  on public.plant_pv_changes (plant_id, date, id);

drop trigger plant_pv_changes_validate_spending on public.plant_pv_changes;

create or replace function public.validate_plant_pv_change_spending()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.spending_id is not null and not exists (
    select 1
    from public.plant_spendings
    where id = new.spending_id
      and plant_id = new.plant_id
      and type = new.type
  ) then
    raise exception 'Linked PV spending must match the event plant and type';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(new.operations) operation
    where coalesce(operation ->> 'kind', '') not in (
      'increase_field',
      'add_field',
      'decrease_field',
      'remove_field'
    )
  ) then
    raise exception 'PV change contains an unsupported operation';
  end if;

  if new.type = 'improvement' and exists (
    select 1
    from jsonb_array_elements(new.operations) operation
    where coalesce(operation ->> 'kind', '') not in ('increase_field', 'add_field')
  ) then
    raise exception 'Improvement PV changes may only increase capacity';
  end if;

  return new;
end;
$$;

create trigger plant_pv_changes_validate_spending
before insert or update on public.plant_pv_changes
for each row
execute function public.validate_plant_pv_change_spending();

drop trigger plant_spendings_preserve_pv_change_type on public.plant_spendings;
drop function public.prevent_non_improvement_pv_change_spending();

create function public.prevent_incompatible_pv_change_spending()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (
    select 1
    from public.plant_pv_changes
    where spending_id = new.id
      and (
        plant_id is distinct from new.plant_id
        or type is distinct from new.type
      )
  ) then
    raise exception 'A spending linked to PV changes must keep its plant and type';
  end if;

  return new;
end;
$$;

create trigger plant_spendings_preserve_pv_change_linkage
before update of plant_id, type on public.plant_spendings
for each row
execute function public.prevent_incompatible_pv_change_spending();
